language: r

sudo: false

addons:
  apt:
    packages:
      - libhunspell-dev
      - libpoppler-cpp-dev

before_install:
  - sh -e /etc/init.d/xvfb start

r_github_packages:
  - jimhester/covr
  - jeroenooms/hunspell
  - trinker/textclean
  - trinker/textshape
  - trinker/syllable

notifications:
  email:
    on_success:      change
    on_failure:      change

after_success:
  - Rscript -e 'covr::coveralls()'

r_build_args: "--resave-data=best"
r_check_args: "--as-cran"

env:
   global:
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1

