language: r

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      r: devel
      before_install:
        - mkdir -p  ~/.R
        - echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode7.2
      brew_packages: hunspell
      latex: false
    - os: osx
      osx_image: beta-xcode6.1
      latex: false
      disable_homebrew: true

addons:
  apt:
    packages:
      - libhunspell-dev
      - libpoppler-cpp-dev

before_install:
  - sh -e /etc/init.d/xvfb start

r_github_packages:
  - jimhester/covr
  - Rdatatable/data.table
  - trinker/lexicon
  - jeroenooms/hunspell
  - trinker/textclean
  - trinker/textshape
  - trinker/syllable

notifications:
  email:
    on_success:      change
    on_failure:      change

after_success:
  - Rscript -e 'covr::coveralls()'

r_build_args: "--resave-data=best"
r_check_args: "--as-cran"

env:
   global:
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1

